### ISSUE TITLE
Is Mite wrapper necessary?

### ISSUE THREAD

**Issue by qubitz** [Exonto/TSquaredBot#1]
Without knowing much JavaScript, it *seems* possible to add custom functions and properties to 'Creeps' objects. If so, then I think we should be doing that. Otherwise it will get annoying to constantly refer to "mite.creep.this" and "mite.creep.that" for example. Did not do much research...so I'm likely wrong.

**Comment by Exonto** [comment]
Yes, that is a valid possibility. If we decide to go that route we will need to do that soon. Thankfully, little will have to change to accomplish that.

**Comment by Exonto** [comment]
https://www.w3schools.com/jsref/jsref_prototype_math.asp

This is doing exactly what we want

**Comment by Exonto** [comment]
The difference is that this actually has the constructor being defined, which seemed to be the problem.

**Comment by Exonto** [comment]
Alright, figure it all out and we are using CreepExtension now.
